name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: cargo-build
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          
      - uses: actions/checkout@v3
      
      - name: cargo-test
        run: cargo test --verbose
